//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsMVCManager.Models
{
    using System;
    
    public enum EnumModele : int
    {
        Polo = 1,
        Passat = 2,
        Golf = 3,
        P301 = 4,
        P407 = 5,
        P508 = 6,
        Megane = 7,
        Clio = 8,
        Symbol = 9
    }
}
