//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsMVCManager.Models
{
    using System;
    
    public enum EnumCarburant : int
    {
        Essence = 1,
        Diesel = 2
    }
}
